# NOTE: update this with your service name
service: alert-facebook-scraper-service

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules:
    forceInclude:
      - alert-facebook-scraper-shared-models

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-1
  environment: ${file(./env.json):${opt:stage}}

functions:
  # hello:
  #   handler: handler.hello
  #   events:
  #     - http:
  #         path: hello
  #         method: get

  syncFeed:
    handler: functions/syncFeed/syncFeed.handler

  syncPostComments:
    handler: functions/syncPostComments/syncPostComments.handler

  syncCommentSubcomments:
    handler: functions/syncCommentSubcomments/syncCommentSubcomments.handler

  syncCommentReactions:
    handler: functions/syncCommentReactions/syncCommentReactions.handler
  
  syncPostReactions:
    handler: functions/syncPostReactions/syncPostReactions.handler
